# Generated by Django 2.1.7 on 2019-03-29 16:38

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterevent',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default=backend.models.generate_event_uuid, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default=backend.models.generate_user_uuid, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
