# Generated by Django 2.1.7 on 2019-03-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='event',
            name='require_approve',
            field=models.BooleanField(default=False, verbose_name='注册需要审核'),
        ),
    ]
