# Generated by Django 2.1.7 on 2019-03-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190325_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterevent',
            name='registered_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Transport'),
        ),
    ]
