# Generated by Django 2.1.7 on 2019-03-29 19:33

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190330_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default=backend.models.generate_event_uuid, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transport',
            name='id',
            field=models.CharField(default=backend.models.generate_user_uuid, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transport',
            name='other_detail',
            field=models.TextField(blank=True, verbose_name='详细信息'),
        ),
        migrations.AlterField(
            model_name='userregisterevent',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
