# Generated by Django 2.1.7 on 2019-03-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190330_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregisterevent',
            old_name='registered_transport',
            new_name='transport',
        ),
    ]
