# Generated by Django 2.1.7 on 2019-04-01 04:18

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190330_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='token',
            field=models.CharField(default=backend.models.generate_checkin_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
