# Generated by Django 2.1.7 on 2019-04-01 05:13

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190401_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='token',
            field=models.CharField(default=backend.models.generate_checkin_uuid, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
