# Generated by Django 2.1.7 on 2019-04-22 13:18

import backend.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190401_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activate_token',
            field=models.CharField(default=backend.utils.uuid.generate_uuid, max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
