# Generated by Django 2.1.7 on 2019-04-24 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190422_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_application',
            field=models.BooleanField(default=False, verbose_name='需要填写申请信息'),
        ),
        migrations.AddField(
            model_name='event',
            name='require_attachment',
            field=models.BooleanField(default=False, verbose_name='需要提交申请文件'),
        ),
        migrations.AddField(
            model_name='userregisterevent',
            name='application_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregisterevent',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregisterevent',
            name='date_approved',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='批准时间'),
            preserve_default=False,
        ),
    ]
