# Generated by Django 2.1.7 on 2019-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190424_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
