# Generated by Django 2.2.1 on 2019-05-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20190524_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='checkin_enabled',
        ),
        migrations.AddField(
            model_name='checkin',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CheckIn')),
                ('ure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserRegisterEvent')),
            ],
        ),
    ]
